;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="Inventory.Resources.MisticStawberry",NewTagName="Inventory.Resources.Cheese")
+GameplayTagRedirects=(OldTagName="Inventory.Weapons.Knife",NewTagName="Inventory.Weapons.Hammer")
+GameplayTagRedirects=(OldTagName="Inventory.Weapons.LongSword",NewTagName="Inventory.Weapons.Sword")
+GameplayTagRedirects=(OldTagName="Inventory.Armor.Breastplate.Medieval",NewTagName="Inventory.Armor.Breastplate.Heavy")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Inventory",DevComment="")
+GameplayTagList=(Tag="Inventory.Armor",DevComment="")
+GameplayTagList=(Tag="Inventory.Armor.Breastplate.Heavy",DevComment="")
+GameplayTagList=(Tag="Inventory.Armor.Cloak",DevComment="")
+GameplayTagList=(Tag="Inventory.Armor.Cloak.Blue",DevComment="")
+GameplayTagList=(Tag="Inventory.Armor.Cloak.Red",DevComment="")
+GameplayTagList=(Tag="Inventory.Armor.Gloves",DevComment="")
+GameplayTagList=(Tag="Inventory.Armor.Helmet.Heavy",DevComment="")
+GameplayTagList=(Tag="Inventory.Armor.Helmet.Viking",DevComment="")
+GameplayTagList=(Tag="Inventory.Armor.Legs",DevComment="")
+GameplayTagList=(Tag="Inventory.Armor.Mask.Red",DevComment="")
+GameplayTagList=(Tag="Inventory.Armor.Shoes",DevComment="")
+GameplayTagList=(Tag="Inventory.Resources",DevComment="")
+GameplayTagList=(Tag="Inventory.Resources.BluePotion.Large",DevComment="")
+GameplayTagList=(Tag="Inventory.Resources.BluePotion.Small",DevComment="")
+GameplayTagList=(Tag="Inventory.Resources.Cheese",DevComment="")
+GameplayTagList=(Tag="Inventory.Resources.RedPotion",DevComment="")
+GameplayTagList=(Tag="Inventory.Resources.RedPotion.Large",DevComment="")
+GameplayTagList=(Tag="Inventory.Resources.RedPotion.Small",DevComment="")
+GameplayTagList=(Tag="Inventory.Weapons",DevComment="")
+GameplayTagList=(Tag="Inventory.Weapons.Axe",DevComment="")
+GameplayTagList=(Tag="Inventory.Weapons.Hammer",DevComment="")
+GameplayTagList=(Tag="Inventory.Weapons.Staff",DevComment="")
+GameplayTagList=(Tag="Inventory.Weapons.Sword",DevComment="")

