;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Inventory",DevComment="")
+GameplayTagList=(Tag="Inventory.Armor",DevComment="")
+GameplayTagList=(Tag="Inventory.Armor.Cloak",DevComment="")
+GameplayTagList=(Tag="Inventory.Armor.Cloak.Blue",DevComment="")
+GameplayTagList=(Tag="Inventory.Armor.Cloak.Red",DevComment="")
+GameplayTagList=(Tag="Inventory.Armor.Mask",DevComment="")
+GameplayTagList=(Tag="Inventory.Armor.Mask.Blue",DevComment="")
+GameplayTagList=(Tag="Inventory.Armor.Mask.Red",DevComment="")
+GameplayTagList=(Tag="Inventory.Resources",DevComment="")
+GameplayTagList=(Tag="Inventory.Resources.BluePotion.Large",DevComment="")
+GameplayTagList=(Tag="Inventory.Resources.BluePotion.Small",DevComment="")
+GameplayTagList=(Tag="Inventory.Resources.MisticStawberry",DevComment="")
+GameplayTagList=(Tag="Inventory.Resources.RedPotion",DevComment="")
+GameplayTagList=(Tag="Inventory.Resources.RedPotion.Large",DevComment="")
+GameplayTagList=(Tag="Inventory.Resources.RedPotion.Small",DevComment="")
+GameplayTagList=(Tag="Inventory.Weapons",DevComment="")
+GameplayTagList=(Tag="Inventory.Weapons.Axe",DevComment="")
+GameplayTagList=(Tag="Inventory.Weapons.Knife",DevComment="")
+GameplayTagList=(Tag="Inventory.Weapons.LongSword",DevComment="")
+GameplayTagList=(Tag="Inventory.Weapons.NightsEdge",DevComment="")
+GameplayTagList=(Tag="Inventory.Weapons.Shadowbane",DevComment="")
+GameplayTagList=(Tag="Inventory.Weapons.Staff",DevComment="")

